#+TITLE: Praktische Umsetzung
\chapter{Praktische Umsetzung}

* Gehäuse
Das Gehäuse muss so dimensioniert sein, dass es Eurorack-kompatible Module beherrbergen kann. Wichtig ist dabei vor allem der vertikale Abstand der Schienen, auf welchen die Module befestigt werden. Dieser misst laut dem /Doepfer System A100 Handbuch Seite 3/ 3 HE (Höheneinheiten). 1 HE beträgt dabei \SI{44.45}{\milli\meter}. Die Breite der Module beträgt ein Vielfaches von \SI{5.08}{\milli\meter}, beziehungsweise 0.2 Zoll. Manche Gehäuse, wie beispielsweise die von der Firma Intellijel hergestellten, können auch Module welche nur eine Höheneinheit hoch sind beherrbergen.

* Spannungsquelle
Eurorack Synthesizer arbeiten mit Spannungen von \SI{24}{\volt} peak to peak, benötigen also eine Spannungsquelle, welche \SI{-12}{\volt} bis \SI{+12}{\volt} bereitstellen kann. Manche Module benötigen außerdem eine Seperate \SI{5}{\volt} Leitung um zum Beispiel Microcontroller zu betreiben. Eine beliebte Wahl in der DIY-Szene ist die Mean Well RT65B PSU, da sie \SI{\pm 12}{\volt} und \SI{5}{\volt} mit einer genügenden maximalen Stromstärke/Leistung bereitstellt um ein Anfängersystem zu versorgen und verhältnismäßig günstig ist.

* Spannungsverteilung
Die Module werden über ein 10 Pin IDC-Flachbandkabel mit Strom versorgt. Dabei sind die mittleren 6 Pins durchverbunden und geerdet. Die äußeren vier Pins sind paarweise verbunden und liefern jeweils \SI{+12}{\volt} und \SI{-12}{\volt}. Der PIN, welcher auf \SI{-12}{\volt} liegt, ist üblicherweise rot gekennzeichnet.

* Module

Im Folgenden werden die Module, welche den Synthesizer ausmachen, beschrieben. Alle dieser Module bestehen aus einem Panel, welches als User Interface dient und einer Platine, welche mit den elektronischen Komponenten bestückt ist. Panels besitzen mindestens eine Audiobuchse um CV, Audio, Triggersignale und andere Arten von Spannungssignalen auszugeben und oft eine beliebige Auswahl an Audioeingängen für Kontrollspannungen, Audio-Inputs und ähnlichem und andere Interfacekomponenten wie Potentiometern, Schaltern, Knöpfen, LEDs und weiterem.

Die elektronischen Komponenten können durch verschiedene Methoden zusammengeschalten werden, Beispiele dafür sind:
+ Breadboards:
  vor allem geeignet zum erstellen von Prototypen
+ THT Platinen:
  eine schnelle Methode um eine einzelne Platine zu fertigen
+ Selbst geätzte oder vorgefertigte Platinen:
  eine Methode mit relativ geringem Fehlerpotential, ideal wenn eine größere Anzahl gleichartiger Platinen gefertigt werden sollen, beispielsweise für DIY-Kits
+ "Deadbug" Methode:
  Eletronische Komponenten werden ohne Platine "point to point" miteinander verlötet. Resultiert meist in Spaghettiähnlichen Strukturen, kann bei gekonnter Ausführung jedoch in sehr ästhetischen Schaltkreisen resultieren.

Die elektronischen Komponenten unserer Module sind auf THT-Platinen gelötet. Diese Platine wird im rechten Winkel in der Mitte des Panels befestigt. Interface-Komponenten welche vom Benutzerpanel aus zugänglich sein sollen werden über längere Kabel und Schraubklemmen auf der Platine verbunden.

Als Material für Panels sind Bleche, Dünne Holz-/Plastikplatten oder ähnliches geeignet, zu bedenken ist dabei die 

+ Dicke des Materials:
  Zum Bestücken sollte eine bestimmte Dicke nicht überschritten werden (abhängig von den gewählten Potentiometern, Audiobuchsen, Schaltern und Knöpfen)
+ Bearbeitbarkeit:
  Es müssen Löcher für Interfacekomponenten gebohrt oder gestanzt werden, und das Material muss zugeschnitten werden
+ Beschriftbarkeit:
  Für einfachere Zugänglichkeit und für bessere Ästhetik sollten die Panels bemalt und/oder beschriftet werden

Wir benutzen eine dünne, schwarz lackierte Holzplatte als Material für unsere Panels, diese bekleben wir mit transparenter Folie welche mit weißem permanent Marker beschriftet werden kann.

#+INCLUDE: modules/oscillator.org

#+INCLUDE: modules/mixer.org

#+INCLUDE: modules/lfo.org

#+INCLUDE: modules/noise.org

#+INCLUDE: modules/ar.org
