#+TITLE: Schluss
\chapter{Schluss}

* Erreichung des gesetzten Ziels
Es war möglich, die Zielsetzung der vorliegenden Diplomarbeit im Großteil zu erfüllen. Diese umfasst die Konstruktion eines Synthesizers im Eurorack-Format mit allen nötigen Modulen, um eine Signalverarbeitungskette, welche zur klassischen subtraktiven Klangsynthese fähig ist, zu bilden. Folgende Bestandteile dieses Synthesizers wurden recherchiert, geplant und als Modul fertiggestellt:

+ Oszillator(-en) mit hörbarer Frequenz
+ Oszillator(-en) mit niedriger Frequenz \ac{LFO}
+ Mixer Modul (passiv)
+ Generator von (weißem) Rauschen
+ Attack-Release-Hüllkurvengenerator

Vernachlässigt wurde, aufgrund des hohen Komplexitätsgrades und der eher nebensächlichen Relevanz, der Sequenzer. Dieser wird mit einem manuell betätigbaren Knopf, welcher bei Betätigung den Kontrollspannungseingang des Hüllkurvengenerators auf \SI{5}{\volt} legt, ersetzt.

* Erlangte Erkenntnisse 
Es wurden einige weitere Erkenntnisse bei der Durchführung des Projektes erlangt, nämlich:

** Material für Deckplatten
Zwar ist Holz verhältnismäßig leicht zu bearbeiten, jedoch wird für die Deckplatte eines Eurorack-Modules ein relativ dünnes Material benötigt, damit Komponenten wie Audiobuchsen befestigt werden können. Außerdem entstehen beim Bohren von lackierten Holzplatten unschöne (ausgefranste) Bohrstellen. Bei zukünftigen Modulen wäre also ein geeigneteres Material wie zum Beispiel ein Blech zu wählen.

** Material für Platinen
THT-Platinen eignen sich sehr gut für simple Schaltkreise, jedoch werden sie schnell unübersichtlich, sobald ein komplexerer Schaltkreis gelötet werden soll. Das führt zu Problemen in der Fehlerfindung. Vorgeätzte Platinen, bei welchen nur noch Komponenten wie Wiederstände, Transistoren und ähnliches festgelötet werden müssen sind hier weniger Fehleranfällig.

** Recherche nach simplen Schaltkreisen
Da die Fehleranfälligkeit eines Schaltkreises bei höherer Komplexität stark steigt und auch ein höherer Aufwand benötigt wird, sollten möglich simple Schaltkreise gewählt werden. Die Klangerzeugung ist keine exakte Wissenschaft, sondern eher eine Kunst und so ist es durchaus kein Nachteil wenn bestimmte Module etwas ungenau funktionieren, und einen eigenen Charakter aufweisen.

** Reihenfolge der Konstruierten Module
Die Module sollten, vor allem bei einem Projekt mit fixer Deadline wie es eine Diplomarbeit ist, in der Reihenfolge ihrer Wichtigkeit gebaut werden. So ist es beispielsweise nicht sinnvoll, einen Hüllkurvengenerator zu konstruieren, bevor ein anzusteuernder \ac{VCA} existiert.

** Sonstiges 
Gelernt und vertieft wurden außerdem:
+ Arbeiten mit \LaTeX
+ Löten und Arbeiten mit Elektronischen Bauteilen
+ Bearbeitung von Holz
+ Recherche, Planung und Durchführung eines Projektes mit vielen Facetten
+ Sinnvolle Arbeitsteilung je nach Stärken der Teammitglieder
