#+TITLE: Theoretische Grundlagen
#+bibliography: ../references.bib
\chapter{Theoretische Grundlagen}

* Klangsynthese
Das wort *Synthese* bedeutet in etwa zusammensetzen oder zusammenfügen [cite:@duden:synthese] beschreibt also das Erschaffen von etwas neuem durch die Vereinigung von kleineren Teilen, Klangsynthese bedeutet also, aus grundlegenden Klangwellen komplexere Klänge zu erzeugen.

Ein *Synthesizer* ist ein (meist elektronisches) Instrument, welches zur Klangsynthese fähig ist. Während die meisten herkömmlichen analogen Instrumente nur eine oder wenige unterschiedliche Klangfarben erzeugen können, ist eine der Kernaufgaben eines Synthesizers das Erzeugen von Klängen mit beliebig änderbarer Klangfarbe. Zwar können Synthesizer auch herkömmliche Instrumente imitieren, vor allem sind sie jedoch das Mittel der Wahl, wenn unnatürliche und untypische Klangfarben erzeugt werden sollen, oder wenn sich die Klangfarbe eines Tones ändern soll, während er gespielt wird.

** Klangwellen
Klangwellen sind die Grundbausteine der Klangsynthese. Sie können in verschiedenen Medien vorkommen, wichtig sind für uns vor allem als Spannung ausgedrückte Klangwellen, welche wir mit Elektronik manipulieren können und Schallwellen in der Luft als Endprodukt. Weitere Formen von Klangwellen sind zum Beispiel die Schwingungen einer Gitarrensaite oder Lautsprechermembran oder Elektromagnetische Wellen, zum Beispiel beim Funk.

Die Tonhöhe einer Klangwelle hängt von ihrer *Frequenz*, also von der Geschwindigkeit ab, in welcher sie schwingt. Dabei nimmt das menschliche Gehirn Töne auf eine logarithmische Art und Weise wahr, um eine große Bandbreite an Tonhöhen differenzieren zu können. Deshalb entspricht ein Ton mit der doppelten Frequenz dem selben Ton eine Oktave höher. Die Einheit für Frequenzen ist \si{\hertz}, was $\frac{1}{\si{\second}}$ entspricht, also wie oft die Welle in einer Sekunde schwingt.

Die Lautstärke einer Klangwelle, also ihre *Amplitude*, wird ebenfalls auf eine logarithmische Art und Weise wahrgenommen. So bedeutet eine Steigerung der Lautstärke um 20 \si{\dB} eine verzehnfachung der Amplitude, also des Energieniveaus der Welle. Die Amplitude einer Welle entspricht der Differenz ihrer Maximal- und Minimalwerte. Die Einheit der Amplitude einer Welle hängt von ihrem Medium ab, bei einer Spannungswelle die von einem Oszillator generiert wird, wird die Amplitude beispielsweise in Volt angegeben. Die Amplitude einer Schallwelle wird üblicherweise in \si{\dB} angegeben.

Klangwellen können verschiedene Formen besitzen, die grundlegende Form ist eine *Sinuswelle*. Das menschliche Ohr empfindet eine sinusförmige Schallwelle als "`rein", da sie eine einzelne Frequenz ohne *Obertöne* repräsentiert. Weitere einfache Formen sind Rechteckswellen, Sägezahnwellen und Dreieckwellen. Diese Wellenformen besitzen neben ihrer Grundfrequenz weitere Obertöne, welche dem Klang Farbe verleihen. Teilt die Frequenz eines solchen Obertons die Frequenz des Grundtones ganzzahlig, wird er als Harmonisch, also wohlklingend empfunden.

** Klangerzeugung
Die für die Klangsynthese benötigten grundlegenden Klangwellen können aus verschiedensten Quellen stammen. Die häufigste davon ist wohl ein *Oszillator*, welcher durchgehende Klangwellen mit einer einfachen Wellenform wie zum Beispiel einem Sinus oder einer Rechteckswelle generiert. In einem Späteren Teil dieser Dokumentation wird Aufbau und Design eines solchen Oszillators beschrieben.

Abgesehen davon können eine breite Spanne von elektronischen Musikinstrumenten / Klangquellen wie E-Gitarren, Thereminen oder Radios und Kassettenspielern die zu modifizierenden Klangwellen für einen Synthesizer bereitstellen.

** Subtraktive Klangsynthese
Das Prinzip der Subtraktiven Klangsynthese besteht darin, Grundtöne mit vielen Obertönen zu filtern, um Töne mit einer gewünschten Klangfarbe zu erzeugen. Durch einen *Filter* wird die Amplitude von Teilwellen unter einer bestimmten Frequenz (=> high-pass Filter) oder über einer bestimmten Frequenz (=> low-pass Filter) verringert, wodurch zum Beispiel unangenehm hohe Obertöne gefiltert werden können.

Nach einem solchen Filter wird oft ein Spannungskontrollierter *Verstärker* (VCA) geschalten, welcher die Amplitude des Eingangssignals proportional zur angelegten Kontrollspannung skaliert. Diese Kontrollspannung kann beispielsweise durch einen LFO oder Hüllkurvengenerator bereitgestellt werden. Dadurch kann einem durchgehenden Signal Rhythmus verliehen werden.

** Additive Klangsynthese
Laut Fourier [[https://mathworld.wolfram.com/FourierTransform.html]] kann jegliche Art von Wellenform durch eine Serie von Sinuswellen ausgedrückt werden. Das Prinzip der additiven Klangsynthese besteht somit darin, eine Vielzahl von Sinuswellen mit unterschiedlichen Amplituden und Frequenzen zu Kombinieren, (beispielsweise durch einen Mixer) um Klänge mit jeglicher erdenklichen Klangfarbe zu erzeugen. Idealerweise wird jede grundlegende Sinuswelle durch eine seperate Hüllkurve moduliert um einen Klang mit laufend verändernder Klangfarbe zu erzeugen. [cite:@raffaseder] Da dies mit einer steigenden Anzahl an grundlegenden Sinuswellen eine technische Herausforderung darstellt, sind additive Synthesizer meist Digital ausgeführt, ein analoges Beispiel für einen additiven synthesizer wäre eine Orgel.

** Vocoder
Ein Vocoder basiert auf dem Prinzip, ein Signal (meist eine Stimme) mittels mehrerer Band-Pass Filter in seine Frequenzbestandteile aufzuteilen. Anschließend wird dieses Frequenzspektrum auf der Basis von weißem Rauschen wieder aufgebaut um einen als gesprochenes Wort zu erkennenden Klang zu erzeugen. Ein Vocoder arbeitet somit sowohl mit subtraktiver Soundsynthese bei der Analyse des Frequenzspektrums als auch mit additiver Soundsynthese beim wieder zusammensetzen des analysierten Klangs.

* Geschichte
Bereits im frühen 20. Jahrhundert wurden Elektronische Schaltkreise dazu benutzt, Klänge zu erzeugen. Damals noch mit Vakuumröhren statt Transistoren hergestellt, stellt das *Theremin* eines der ältesten heute noch verwendeten Elektronischen Musikinstrumente dar.

Der erste vollwertige elektronische Synthesizer, welcher auch als solcher bezeichnet wurde, war der *RCA Music Synthesizer*, eine raumhohe Maschine welche als Gemeinschaftsprojekt zwischen den amerikanischen Universitäten von Princeton und Columbia entstanden war. Statt mit einer Klaviertastatur spielte, beziehungsweise programmierte, man diesen Synthesizer erst mittels Lochkarten und konnte dann gewisse Aspekte des Klanges dynamisch während das Stück spielte ändern.

Das Konzept eines modularen Synthesizers und damit auch das Konzept der Kontrollspannung wurde erstmals von Robert Moog in seiner Arbeit mit dem Titel "`VOLTAGE-CONTROLLED ELECTRONIC MUSIC MODULES"' Dokumentiert. \cite{moog1964} Der *Moog Modular Synthesizer*, welcher auf diesen Prinzipien basiert, führte viele heute noch aktuelle Standards ein, wie zum Beispiel die Kontrollspannungsarten Trigger und \SI{1}{\volt} pro Oktave. Spätestens mit dem 1968 erschienenen Album "`Switched-On Bach"' wurde der Synthesizer als vollwertiges Instrument im Mainstream akzeptiert.

Während die Synthesizer von Moog mit dem Prinzip der Subtraktiven Klangsynthese arbeiteten, wurden zur gleichen Zeit, auf der anderen Seite Amerikas, erste Synthesizer mit additiver Klangsynthese hergestellt. Die von *Donald Buchla* hergestellten Synthesizer boten dem Benutzer beinahe grenzenlose Freiheit über die Farbe der erzeugten Klänge an. Dennoch blieb die Subtraktive Klangsynthese, wohl aufgrund größerer Intuitivität und besserer technischer Umsetzbarkeit das vorherrschende Prinzip.

Obwohl Moog als Vater der Modularen Klangsynthese gilt, ist eines der bekanntesten und beliebtesten Produkte der Firma Moog der fix verkabelte *Minimoog*. Dieser als live-Instrument gedachte Synthesizer führte ein Lautstärkerad und ein Tonhöhenveränderungsrad ein, mit welchem Töne ähnlich wie beim Saitenziehen bei einer Gitarre verändert werden können.

Die 70er und 80er Jahre waren vor allem von digitalen Synthesizern geprägt. Das von der Firma "`New England Digital"' hergestellte Synclavier I war der erste Synthesizer welcher Frequenzmodulation, ein Beispiel für additive Klangsynthese, anbot, der von Yamaha hergestellte *DX7*, brachte dieses Konzept in den Mainstream. Die Glockenartigen Klänge welche charakteristisch für diese Art der Klangsynthese sind, prägten den Großteil der 80er Jahre und sind auch heute noch häufig im Pop und im Schlager zu finden.

Das Konzept der Modularen Synthesizer schien beinahe vergessen, bis im Jahre 1992 Dieter Döpfer, gemeinsam mit der Band Kraftwerk das modulare Synthesizersystem *A-100* entwarf. Die quelloffene Natur dieses Systems ermöglichte es anderen Herstellern wie auch der Firma Moog kompatible Module herzustellen, wodurch ein de-facto Standard entstand, heute bekannt als Eurorack, was zu einer renaissance der modularen Synthesizer führte.

Die Dokumentation für diesen Synthesizer, den A-100, stellt auf direkte oder indirekte Weise die Grundlage für die meisten Aspekte des in dieser Dokumentation beschriebenen Systems dar.

* Das Eurorack Format

1996 veröffentlichte Doepfer Musikelektronik GmbH eine Reihe an Synthesizermodulen. Schnell wurden kompatible Module von anderen Herstellern hergestellt, wodurch das Eurorack Format zum de-facto Standard für modulare Synthesizer wurde. Heute gibt es tausende von Eurorack Modulen, hergestellt von bekannten Firmen wie Moog, Roland, Behringer und auf Eurorack spezialisierten Herstellern wie Make Noise. Des weiteren gibt es eine lebendige DIY-szene mit vielen öffentlichen Designs, Anleitungen, Schematics, vorbereiteten Kits zum zusammenbauen und mehr.

** Kontrollspannung
Essentiell bei Eurorack Modulen ist, dass viele Parameter nicht nur durch den Benutzer (durch Knöpfe, Potentiometer, etc) sondern auch durch andere Module mithilfe von sog. Kontrollspannung (CV) ansteuerbar sind. So kann z.B die Frequenz eines Oszillators, der Cutoff eines Filters, Attack und Releaselänge eines Envelopes und ähnliches durch Kontrollspannung kontrolliert werden; Diese Kontrollspannung kann wiederum aus verschiedensten Modulen wie z.B. einem MIDI Interface, einem LFO, einem Envelope Generator wie zum Beispiel ADSR oder sogar einem anderen Audiosignal kommen. Dadurch entsteht ein Netzwerk an elektronischen Schaltungen welche sich gegenseitig beeinflussen und hochschaukeln, was zu idealerweise wohlklingenden, jedoch in jedem Fall interessanten Effekten führt.

Besonders für Eurorack und für modulare Synthesizer im Generellen hat dieses Konzept einen hohen Stellenwert, da bei solchen Systemen Audiosignale und Kontrollspannungen nicht fix verkabelt sind, sondern vom Benutzer flexibel mit \SI{3.5}{\milli\meter} mono Klinkensteckern, sogenannten *Patchkabeln* geschalten werden können. Der Unterschied zwischen Audiosignalen und Kontrollspannung liegt rein im Verwendungszweck, oft können auch Audiosignale als Kontrollspannung dienen. Es gibt verschiedene Arten von Kontrollspannung, welche sich primär durch ihren Verwendungszweck unterscheiden:

*** Hüllkurve
Hüllkurven besitzen meist einen positiven Spannungsbereich. Sie werden oft zum Ansteuern von Spannungskontrollierbaren Verstärkern (VCA) benutzt. Hüllkurven treten oft in Form von *ADSR* (Attack, Decay, Sustain, Release) auf, diese Art von Hüllkurve beschreibt den Verlauf der Lautstärke eines Tones beim Drücken einer Taste. \cite{envelopes}

**** Attack
Der "`Attack"' Wert gibt an, wie lange der Ton nach dem Drücken der Taste braucht, um auf seine maximale Lautstärke anzuschwellen.

**** Decay
Nachdem der Ton seine maximale Lautstärke erreicht hat, schwillt er auf eine niedrigere Lautstärke ab. Der Decay-Wert, gibt an, wie lange der Ton benötigt, um diese niedrigere Lautstärke zu erreichen.

**** Sustain
Im Unterschied zu den Anderen Parametern ist der Sustain-Wert eine Amplitude anstatt einer Zeit. Der eingestellte Wert gibt an, auf welche Lautstärke das Signal nach dem Ablaufen der Decay-Zeit abschwillt. Die eingestellte Lautstärke ist konstant, solange die Taste gedrückt bleibt.

**** Release
Nach dem Loslassen der Taste benötigt der Ton eine gewisse Zeit, um eine Lautstärke von 0 zu erreichen. Diese Zeit wird über den Release-Parameter eingestellt.

*** Trigger
Triggersignale sind steigende Flanken direkt gefolgt von einer fallenden Flanke, meist zwischen \SI{0}{\volt} und \SI{5}{\volt}. Ihr Zweck ist es, Prozesse, wie etwa das fortschreiten eines Sequencers, auszulösen.

*** Gate
Ähnlch wie ein Triggersignal ist ein Gate eine steigende Flanke gefolgt von einer fallenden Flanke zwsichen \SI{0}{\volt} und \SI{5}{\volt}. Im Unterschied zum Trigger ist jedoch der Zeitliche Abstand zwischen steigender und fallender Flanke oft beträchtlich länger und spielt eine wichtige Rolle. Gate-Signale werden oft verwendet um den Zustand einer Keyboardtaste zu beschreiben.

*** Audio
Audiosignale sind Spannungen, meist zwischen \SI{-5}{\volt} und \SI{5}{\volt}, welche an einen Verstärker oder Lautsprecher angelegt werden können um Schall zu erzeugen. Sie können auch zur Weiterverarbeitung von einem Modul zum anderen geschickt werden und sogar als Kontrollspannung verwendet werden. Man kann Audiosignale als Kontrollspannungen, welche zum Ansteuern von Lautsprechern geeignet sind, sehen.
