* Attack-Release Hüllkurvengenerator
Aufgrund der Komplexität eines vollständigen ADSR haben wir uns dazu entschieden einen simpleren AR (Attack-Release) Hüllkurvengenerator zu bauen. Dieser besitzt einen Eingang für Kontrollspannung, an welchen ein Gate-Signal angelegt werden kann und zwei Drehpotentiometer, durch welche die Parameter Attack und Release eingestellt werden können. Attack stellt dabei die Zeit dar, die das Signal nach dem Drücken einer Taste, beziehungsweise dem Anfang eines eingehenden Gate-Signals benötigt, um seinen Maximalwert zu erreichen. Gate stellt die Zeit dar, die nach Ende des Gate-Signals benötigt wird, bis die Spannung der generierten Hüllkurve wieder abschwillt.

** Spezifikationen
** Elektronik
In unserer Umsetzung wird das Potential des Kontrollspannungseingangs, an welchem ein Gate-Signal erwartet wird, von einem Operationsverstärkers auf 12V verstärkt. Durch den oberen Signalpfad füllt sich ein großer Kondensator, die Spannung, welche am Kondensator anliegt, wird gleichzeitig von einem Spannungsfolger gepuffert, da diese gleichzeitig die Ausgangsspannung darstellt. Wird das Gate geschlossen fällt die Spannung über den unteren Signalpfad wieder ab. Durch die Potentiometer kann man die Geschwindigkeit dieser beiden Prozesse kontrollieren.
** Schematics
** Benutzung
