* Oszillator x2
Dieses Modul ist ein simples signalerzeugendes Modul, welches zwei voneinander unabhängige Rechteckswellen im hörbaren Bereich generiert.

\begin{circuitikz}
\ctikzset{bipoles/oscope/waveform=square}
\draw{node[oscopeshape](){}};
\end{circuitikz}

** Spezifikationen
Oszillator 1:
+ Spannung: bis zu 10[[file:~/Documents/diplomarbeit/dokumentation/content/hauptteil.org::*Vpp][Vpp]]
+ Frequenzbereich: \SI{30}{\hertz} bis \approx\SI{2000}{\hertz}

Oszillator 2:
+ Spannung: bis zu 10[[file:~/Documents/diplomarbeit/dokumentation/content/hauptteil.org::*Vpp][Vpp]]
+ Frequenzbereich: \SI{18}{\hertz} bis \approx\SI{2000}{\hertz}
  
** Elektronik
Als Grundlage dient ein einfacher "`Resistor-Capacitor"' Schwingkreis, welcher einen Schmitttrigger nutzt. Das resultierende Signal wird durch einen Spannungsfolger gepuffert, da sonst die Oszillation zusammenbricht. Des weiteren wird das Signal danach AC gekoppelt, um das positive Offset der Ozillation zu entfernen und ein weiteres Mal gepuffert. Darauf folgt ein einfacher variabler Spannungsteiler als Dämpfungsglied, um die Amplitude regulieren zu können.

** Schematics

#+INCLUDE: schematics/oscillator.org

** Benutzung
Das Panel ist aufgeteilt in einen linken und rechten Oszillator, alle Elemente auf einer Seite gehören zu jeweils einem Oszillator. Die oberen beiden Potentiometer dienen zur Steuerung der [[file:~/Documents/diplomarbeit/dokumentation/content/theoretische_grundlagen.org::*Frequenz][Frequenz]], die unteren beiden dienen zur Steuerung der [[file:~/Documents/diplomarbeit/dokumentation/content/theoretische_grundlagen.org::*Amplitude][Amplitude]] des Signals. Die Audiobuchsen dienen als Output. Der Schalter links oben aktiviert das Modul, die Oszillatoren sind nicht seperat voneinander an/ausschaltbar.
